"""Generate a Substack-ready rich-text copy page from the daily digest."""

import logging
from datetime import date
from pathlib import Path

import config

logger = logging.getLogger(__name__)

SUBSTACK_DIR = config.BASE_DIR / "substack"
SUBSTACK_DIR.mkdir(exist_ok=True)


def _build_post_content(
    digest_html: str,
    pubmed_articles: list,
    news_articles: list,
    regulatory_articles: list,
    trials: list,
    today: str,
) -> str:
    """Build the Substack post body as clean HTML (no wrapper/styles)."""
    parts = [
        f"<h2>TAVR Daily Digest &mdash; {today}</h2>",
        f"<p><em>{len(pubmed_articles)} journal articles | "
        f"{len(news_articles)} news items | "
        f"{len(regulatory_articles)} regulatory updates | "
        f"{len(trials)} trial updates</em></p>",
        "<hr>",
        digest_html,
    ]

    if pubmed_articles:
        parts.append("<h2>Journal Article Sources</h2><ul>")
        for a in pubmed_articles:
            parts.append(
                f'<li><a href="{a["url"]}">{a["title"]}</a> &mdash; '
                f'{a["journal"]}, {a["pub_date"]}</li>'
            )
        parts.append("</ul>")

    if news_articles:
        parts.append("<h2>News Sources</h2><ul>")
        for a in news_articles:
            parts.append(
                f'<li><a href="{a["url"]}">{a["title"]}</a> &mdash; '
                f'{a.get("source_name", "")}, {a["pub_date"]}</li>'
            )
        parts.append("</ul>")

    if regulatory_articles:
        parts.append("<h2>Regulatory Sources</h2><ul>")
        for a in regulatory_articles:
            parts.append(
                f'<li><a href="{a["url"]}">{a["title"]}</a> &mdash; '
                f'{a.get("source_name", "")}, {a["pub_date"]}</li>'
            )
        parts.append("</ul>")

    if trials:
        parts.append("<h2>Clinical Trial Sources</h2><ul>")
        for t in trials:
            parts.append(
                f'<li><a href="{t["url"]}">{t["nct_id"]}</a>: {t["title"]} '
                f'&mdash; {t["status"]}, {t["sponsor"]}</li>'
            )
        parts.append("</ul>")

    parts.append("<hr>")
    parts.append(
        "<p><em>Generated by TAVR Digest Agent using Claude AI. "
        "Sources: PubMed/NCBI, TCTMD, Cardiovascular Business, FDA, CMS, "
        "ClinicalTrials.gov, Yahoo Finance.</em></p>"
    )

    return "\n".join(parts)


COPY_PAGE_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>TAVR Digest &mdash; {date} &mdash; Copy to Substack</title>
<style>
  * {{ box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    margin: 0;
    padding: 0;
    background: #f0f0f0;
  }}

  /* Toolbar fixed at top */
  .toolbar {{
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    z-index: 100;
    background: #1a365d;
    color: white;
    padding: 12px 24px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    box-shadow: 0 2px 8px rgba(0,0,0,0.2);
  }}
  .toolbar h1 {{
    margin: 0;
    font-size: 16px;
    font-weight: 600;
  }}
  .toolbar .actions {{
    display: flex;
    gap: 12px;
    align-items: center;
  }}
  .toolbar button {{
    background: #48bb78;
    color: white;
    border: none;
    padding: 10px 24px;
    border-radius: 6px;
    font-size: 15px;
    font-weight: 600;
    cursor: pointer;
    transition: background 0.15s;
  }}
  .toolbar button:hover {{
    background: #38a169;
  }}
  .toolbar button.copied {{
    background: #2d3748;
  }}
  .toolbar .instructions {{
    font-size: 13px;
    opacity: 0.9;
  }}

  /* The content area that gets copied */
  #substack-content {{
    max-width: 680px;
    margin: 80px auto 40px;
    background: white;
    padding: 40px;
    border-radius: 8px;
    box-shadow: 0 1px 4px rgba(0,0,0,0.1);
    line-height: 1.7;
    color: #333;
  }}
  #substack-content h2 {{
    color: #1a365d;
    margin-top: 32px;
    padding-bottom: 6px;
    border-bottom: 1px solid #e2e8f0;
  }}
  #substack-content h3 {{
    color: #2d3748;
    margin-top: 24px;
  }}
  #substack-content a {{
    color: #2b6cb0;
    text-decoration: none;
  }}
  #substack-content a:hover {{
    text-decoration: underline;
  }}
  #substack-content ul {{
    padding-left: 20px;
  }}
  #substack-content li {{
    margin-bottom: 6px;
  }}
  #substack-content hr {{
    border: none;
    border-top: 1px solid #e2e8f0;
    margin: 24px 0;
  }}
  #substack-content table {{
    border-collapse: collapse;
    width: 100%;
    margin: 16px 0;
  }}
  #substack-content th, #substack-content td {{
    border: 1px solid #e2e8f0;
    padding: 8px 12px;
    text-align: left;
  }}
  #substack-content th {{
    background: #f7fafc;
    font-weight: 600;
  }}
</style>
</head>
<body>

<div class="toolbar">
  <div>
    <h1>TAVR Digest &mdash; {date}</h1>
    <div class="instructions">Click the button, then paste (Cmd+V) into Substack's editor</div>
  </div>
  <div class="actions">
    <button id="copy-btn" onclick="copyToClipboard()">Copy to Clipboard</button>
  </div>
</div>

<div id="substack-content">
{content}
</div>

<script>
function copyToClipboard() {{
  const content = document.getElementById('substack-content');
  const range = document.createRange();
  range.selectNodeContents(content);
  const selection = window.getSelection();
  selection.removeAllRanges();
  selection.addRange(range);

  // Copy as rich text (preserves formatting for Substack)
  document.execCommand('copy');
  selection.removeAllRanges();

  // Visual feedback
  const btn = document.getElementById('copy-btn');
  btn.textContent = 'Copied!';
  btn.classList.add('copied');
  setTimeout(() => {{
    btn.textContent = 'Copy to Clipboard';
    btn.classList.remove('copied');
  }}, 2000);
}}
</script>

</body>
</html>
"""


def export_substack(
    digest_html: str,
    pubmed_articles: list,
    news_articles: list,
    regulatory_articles: list = None,
    stock_data: dict = None,
    trials: list = None,
) -> dict:
    """Export the digest as a Substack-ready rich-text copy page.

    Generates an HTML page with a 'Copy to Clipboard' button.
    Open it in a browser, click copy, paste into Substack's editor.

    Returns dict with path to the generated file.
    """
    regulatory_articles = regulatory_articles or []
    trials = trials or []

    today = date.today()
    date_str = today.strftime("%Y-%m-%d")
    date_display = today.strftime("%B %d, %Y")

    # Build the post content (just the body, no page wrapper)
    post_content = _build_post_content(
        digest_html, pubmed_articles, news_articles,
        regulatory_articles, trials, date_display,
    )

    # Wrap in the copy-page template
    page_html = COPY_PAGE_TEMPLATE.format(
        date=date_display,
        content=post_content,
    )

    output_path = SUBSTACK_DIR / f"tavr-digest-{date_str}.html"
    output_path.write_text(page_html, encoding="utf-8")
    logger.info(f"Substack copy page saved: {output_path}")

    return {
        "copy_page": str(output_path),
    }
